1.
SELECT EMPNO, ENAME, SAL, DNAME, LOC
FROM EMP
NATURAL JOIN DEPT;


2.
SELECT E.JOB, E.MGR, E.SAL, E.COMM, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.JOB = 'MANAGER';


3.
SELECT E.ENAME,
       E.JOB,
       E.DEPTNO,
       D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND D.LOC = 'CHICAGO';


4.
SELECT E.ENAME AS Employee_Name,
       E.EMPNO AS "Employee No",
       M.ENAME AS Manager_Name,
       M.EMPNO AS "Manager No"
FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO;


5.
SELECT E.ENAME AS Employee_Name,
       E.EMPNO AS "Employee No",
       M.ENAME AS Manager_Name,
       M.EMPNO AS "Manager No"
FROM EMP E
LEFT OUTER JOIN EMP M
ON E.MGR = M.EMPNO
ORDER BY E.ENAME;


6.
DESC SALGRADE;

SELECT E.ENAME,
       E.JOB,
       D.DNAME,
       E.SAL,
       S.GRADE
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
JOIN SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.HISAL;


7.
SELECT E.ENAME,
       D.DNAME
FROM EMP E
RIGHT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;


8.
SELECT E.ENAME AS Employee_Name,
       E.HIREDATE AS Employee_Hiredate,
       M.ENAME AS Manager_Name,
       M.HIREDATE AS Manager_Hiredate
FROM EMP E
LEFT OUTER JOIN EMP M
ON E.MGR = M.EMPNO
WHERE E.HIREDATE > M.HIREDATE;


9.
SELECT EMPNO,
       ENAME,
       DNAME,
       LOC
FROM EMP
JOIN DEPT
USING (DEPTNO)
WHERE JOB = 'ANALYST';


10.
SELECT E.ENAME,
       E.SAL,
       E.MGR,
       D.DNAME
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.SAL > 3000;


11.
SELECT E.EMPNO,
       E.ENAME,
       E.JOB,
       E.DEPTNO,
       D.DNAME,
       D.LOC
FROM EMP E
LEFT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;


12.
SELECT E.ENAME,
       D.DNAME
FROM EMP E
RIGHT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;


13.
SELECT E.EMPNO,
       D.DNAME,
       D.LOC
FROM EMP E
FULL OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;