
SELECT EMPNO, ENAME, DEPTNO
FROM EMP
WHERE DEPTNO = (
    SELECT DEPTNO
    FROM EMP
    WHERE ENAME = 'SCOTT'
);

SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE SAL >
(
    SELECT AVG(SAL)
    FROM EMP
);
-- 3. Display ENAME and JOB who are Managers
-- (Using EXISTS Operator)

SELECT E.ENAME, E.JOB
FROM EMP E
WHERE EXISTS
(
    SELECT 1
    FROM EMP X
    WHERE X.MGR = E.EMPNO
);

-- the least salary of DEPTNO 10
-- (Using ALL Operator)

SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE SAL < ALL
(
    SELECT SAL
    FROM EMP
    WHERE DEPTNO = 10
);

-- DEPTNO and MGR as employee SCOTT,
-- excluding SCOTT.

SELECT EMPNO, ENAME, DEPTNO, MGR
FROM EMP
WHERE (DEPTNO, MGR) =
(
    SELECT DEPTNO, MGR
    FROM EMP
    WHERE ENAME = 'SCOTT'
)
AND ENAME <> 'SCOTT';

SELECT EMPNO, ENAME
FROM EMP
WHERE DEPTNO IN
(
    SELECT DEPTNO
    FROM EMP
    WHERE ENAME LIKE '%R%'
);



SELECT ENAME, DEPTNO, JOB
FROM EMP
WHERE DEPTNO =
(
    SELECT DEPTNO
    FROM DEPT
    WHERE LOC = 'NEW YORK'
);

ACCEPT P_LOC CHAR PROMPT 'Enter Location : '

SELECT E.ENAME,
       E.DEPTNO,
       E.JOB
FROM EMP E
WHERE E.DEPTNO =
(
    SELECT D.DEPTNO
    FROM DEPT D
    WHERE D.LOC = UPPER('&P_LOC')
);

